display_name: Workshop App
publisher_display_name: Unspoken Tech Org
identity_name: com.workshop.app

# Será sobrescrito no CI (a partir do pubspec), mas deixe um valor inicial:
msix_version: 1.0.0.0

logo_path: windows/runner/resources/app_icon.ico
output_path: build/msix

sign_msix: true
certificate_path: windows/signing/workshop-code-signing.pfx
certificate_password: ${CERT_PASSWORD}
install_certificate: false
publisher: CN=Unspoken Tech Org

# Auto-update (Windows App Installer)
app_installer:
  enable: true
  # Usa o IP/host vindo dos Secrets (SERVER_HOST)
  app_installer_uri: \\\\${SERVER_HOST}\\apps\\workshop\\WorkshopApp.appinstaller
  msix_uri: \\\\${SERVER_HOST}\\apps\\workshop\\WorkshopApp.msix
  hours_between_update_checks: 4

capabilities:
  - internetClient
